### ISSUE TITLE
Add a link checker for the documentation

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#100]
Broken links are always a pain for the writer and the reader of the documentation.
Let's use a link checker such as [linkchecker-markdown](https://github.com/scivision/linkchecker-markdown) as part of our test suite in tox.

**Comment by lishanl** [comment]
I have tried to see if there's another Python library that can do link checking in markdown, just to see if there are any potentially better alternative before we incorporate this link checker. There is this [MegaLinter](https://megalinter.github.io/latest/descriptors/markdown_markdown_link_check/) which actually supports linting a lot of other things, e.g. groovy, yml, css, etc.  It can also be used directly in github actions and general CICD.   Maybe you have seen it @hillairet?  It seems too heavy for our needs in the link checking purpose, unless there's a way to only install the markdown link checking module from it.  

So yea, I will add the [linkchecker-markdown](https://github.com/scivision/linkchecker-markdown) if you suggested.

**Comment by hillairet** [comment]
Megalinter looks interesting but potentially heavy too ...
Definitely let's keep it simple for now.
