### ISSUE TITLE
🐛  webhook graphql not found in Azure function app use case

### ISSUE THREAD

**Issue by lishanl** [SatelCreative/spylib#149]
Please open an issue for this. This is separate from this PR

> I just tested this spylib (install it via this branch) in `st-cim` (running as an azure function) and it returned error about graphql file not found like @qw-in mentioned before.
>

_Originally posted by @hillairet in https://github.com/SatelCreative/spylib/issues/143#issuecomment-1166052381_

**Comment by hillairet** [comment]
The top answer of this [stackoverflow](https://stackoverflow.com/questions/4060221/how-to-reliably-open-a-file-in-the-same-directory-as-the-currently-running-scrip) would probably solve it but I don't think I want to experiment with this and risk to encounter issues in other special cases. Better to switch to strings indeed.

I'd keep these strings in a separate file so while you are at it, do you mind creating a folder such that:
```
webhook.py -> webhook/__init__.py
webhook.graphql -> webhook/graphql_queries.py
```

**Comment by lishanl** [comment]
> The top answer of this [stackoverflow](https://stackoverflow.com/questions/4060221/how-to-reliably-open-a-file-in-the-same-directory-as-the-currently-running-scrip) would probably solve it but I don't think I want to experiment with this and risk to encounter issues in other special cases. Better to switch to strings indeed.
> 
> I'd keep these strings in a separate file so while you are at it, do you mind creating a folder such that:
> 
> ```
> webhook.py -> webhook/__init__.py
> webhook.graphql -> webhook/graphql_queries.py
> ```

sure in a separate PR ?

**Comment by hillairet** [comment]
Well yeah a PR for this issue.
