### ISSUE TITLE
Improve store tests organization

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#15]
* Split GraphQL and Rest into two files
* Find out if `pytest.param` also takes named arguments and if so use named arguments
* Split into happy path and failures
* Get rid of side_effects function and use parametrization instead
* Have `base_gql_response` and in parameters have `mod_gql_response` so that the parametrization is minimal

**Comment by Nathan-Nesbitt** [comment]
I don't think it will be possible to assign named arguments, as the expected input is a list not a dict which would be the optimal format for a function.
