### ISSUE TITLE
👽️ Update OAuth flow based on Shopify's new requirements

### ISSUE THREAD

**Issue by lishanl** [SatelCreative/spylib#171]
Shopify has updated their OAuth flow: [Update your embedded app OAuth flow](https://shopify.dev/apps/auth/oauth/update), thus, we need to do so accordingly. 
Specifically, in the [redirect flow](https://shopify.dev/apps/auth/oauth/getting-started#check-for-and-escape-the-iframe-embedded-apps-only), check `embedded` parameter to take the next step.

**Comment by hillairet** [comment]
Is that a frontend issue? To decide to use or not the Shopify app bridge ...
So closing as invalid for now.
