### ISSUE TITLE
Solve breaking changes on httpx 0.23.1 and fastapi 0.87.0

### ISSUE THREAD

**Issue by lishanl** [SatelCreative/spylib#176]
I have updated the `pyproject.toml` to not update the httpx and fastapi to the latest version because they both contain breaking changes. To be dealt with in another PR:
[httpx==0.23.1](https://github.com/encode/httpx/releases/tag/0.23.1), breaking change on url typing, likely to
[fastapi==0.87.0](https://github.com/tiangolo/fastapi/releases/tag/0.87.0), breaking change on testclient 

Please refer to the 2 CI failures in the PR.

_Originally posted by @lishanl in https://github.com/SatelCreative/spylib/issues/175#issuecomment-1350212603_

**Comment by hillairet** [comment]
Let's go further and update all the dependencies in preparation of version 0.9.0.
Is SPyLib working with the latest fastapi?
