### ISSUE TITLE
Migrate/upgrade CI tox to V4 ?

### ISSUE THREAD

**Issue by lishanl** [SatelCreative/spylib#185]
I updated the Tox version to target to v3 to unstuck the CI tests which caused by a tox V4 failure. 
https://github.com/SatelCreative/spylib/actions/runs/5095339976/jobs/9160185371

Do we want to upgrade to tox v4 @hillairet ? Probably create an issue and assign to @rahulpatidar0191 ?

_Originally posted by @lishanl in https://github.com/SatelCreative/spylib/issues/184#issuecomment-1565042202_

**Comment by hillairet** [comment]
I'd say why not.

**Comment by hillairet** [comment]
@rahulpatidar0191 Could you take care of that one so you get familiar with Tox in the process?
