### ISSUE TITLE
Question: Remove environment variable requirement 

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#25]
The OAuth requires that the user of the library knows that certain environment variables need to be set. Can we configure this so the user implements this portion in their application instead of forcing it in the library? 

https://github.com/SatelCreative/satel-spylib/blob/3bfc32f5eee8d632d85ebd5c54e37e3d9966d4a6/spylib/oauth/config.py#L4-L13

For example at the moment to check HMAC we pull in an environment variable:

https://github.com/SatelCreative/satel-spylib/blob/04cfd44ed8b3684512a76a5799a12f989bf91aae/spylib/oauth/validations.py#L40

Could we instead have some way to provide the arguments when we initialize the library?

**Comment by hillairet** [comment]
That's a good one. I brought in the environment variables but now looking at it this way and the hassle of documenting, I'm thinking that it's best to remove it. Now how do we pass this in?
