### ISSUE TITLE
OAuth wrong redirect URI 

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#29]
Currently if you specify a different URI for the shopify callback URI (e.g. `/api/callback`) you will get the following error. 

Oauth error invalid_request: The redirect_uri is not whitelisted 

Looking at the request parameters this is defaulting to `https:URL/callback` which means that it isn't pulling the proper parameter from the init_oauth_router?

```python
oauth_router = init_oauth_router(
    app_scopes=SCOPES,
    user_scopes=SCOPES,
    public_domain=conf.public_domain,
    private_key=conf.private_key,
    post_install=post_install,
    post_login=None,
    install_init_path='/api/shopify/auth',
    callback_path='/api/callback',
)
```

**Comment by Nathan-Nesbitt** [comment]
Looks like this is caused by the current PYPI package being out of date. By installing directly from the repo it is fixed.

**Comment by lishanl** [comment]
this should be resolved in PR https://github.com/SatelCreative/satel-spylib/pull/10.
