### ISSUE TITLE
Shopify expects redirect handling on installation through GUI

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#31]
When creating a new app, Shopify advises you to add the app to a store using their GUI:

![image](https://user-images.githubusercontent.com/12765521/134425413-67d3a56b-0611-4ff0-921a-6ff37a99e057.png)

When you click the button they redirect you to whatever your `app_url` is set to in the Shopify interface. This is normally set to the root of the application.

We are currently requiring the redirect to go to `https://<URL>/api/shopify/auth?shop=<domain>` which doesn't follow what they are expecting in this instance. Should we be handling this and redirecting to the proper location?

To fix this manually, you need to know that you cannot use the GUI to add the app to a store. You must make the call:

`https://<APP_URL>/api/shopify/auth?shop=<domain>`

manually to trigger the install without causing an infinite loop.

**Comment by hillairet** [comment]
> We are currently requiring the redirect to go to https://<URL>/api/shopify/auth?shop=<domain> which doesn't follow what they are expecting in this instance. Should we be handling this and redirecting to the proper location?

Which redirect are we talking about? I'm not following the issue here.

**Comment by Nathan-Nesbitt** [comment]
@hillairet If you wanted to trigger the authentication process for adding the app to a store called `my_store`, you currently redirect the shop owner to `https://my_app_domain.ca/api/shopify/auth?shop=my_store`. Shopify doesn't expect this in their GUI, as they are redirecting to the base URL of the app `https://my_app_domain.ca/api/`. 

I am assuming that they expect us to check that the shop exists when they visit the base URL for the application, then we are expected to redirect along with all of the URL parameters to the actual endpoint if they aren't/ if the token we have on hand isn't valid?

**Comment by hillairet** [comment]
Can you show the app settings?

**Comment by Nathan-Nesbitt** [comment]
The following @hillairet? I've tried both of these with no luck (note the domains are different as my NGROK session expired before I took the last screenshot):

![image](https://user-images.githubusercontent.com/12765521/134933243-a73265e5-a565-45da-bbde-63d1f9c49445.png)

![image](https://user-images.githubusercontent.com/12765521/134933669-8f4b8811-6172-4670-af76-04b48c81b9ef.png)

When I click on the button it redirects me to the App URL attempting to auth and since there's nothing there it just 404's:

![image](https://user-images.githubusercontent.com/12765521/134934141-8b16b972-2899-4766-a2a4-4d53890e243a.png)

**Comment by hillairet** [comment]
So setting priority to low because it only affects the "Test on development store" button in the partners portal

**Comment by qw-in** [comment]
This is likely a wontfix. For the following reasons:
1. For embedded apps, the javascript will likely be responsible for redirecting from `/` to `https://<SERVER_URL>/api/shopify/auth?shop=<domain>`
2. For server side, it is simple enough do add a redirect from `/` to `/api/shopify/auth?shop=<domain>`
