### ISSUE TITLE
Imports not working properly

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#32]
When you install spylib it doesn't appear to install the requirements properly. It isn't finding PyJWT, shortuuid, tenacity, httpx, fastapi, or loguru

**Comment by qw-in** [comment]
Likely due to the currently fragmented package managers / library configuration in python

Probably makes sense to copy the configuration from a popular package already using poetry. sqlmodel seems like a promising example: https://github.com/tiangolo/sqlmodel/blob/main/pyproject.toml

**Comment by hillairet** [comment]
@lishanl @qw-in I believe this is fixed so I'll close it.
