### ISSUE TITLE
Add `__init__` for pydantic classes

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#35]
Based on [some comments](https://github.com/SatelCreative/satel-spylib/pull/23#issuecomment-927882399).

As Pydantic doesn't display the variables that are defined in the class:

![Screenshot from 2021-09-27 06-32-48](https://user-images.githubusercontent.com/12765521/134918849-c34325c6-5137-4f3a-bee3-509fdf9f2c2b.png)

We can add the `__init__` to each of the classes which would allow for VSCode to pick up on what parameters the class takes. This would reduce the time required to look at the docs for required parameters, but would require more code in each class.

**Comment by hillairet** [comment]
So you can do either:
```python
    def __init__(self, **data):
        """My modified docstring"""
        super().__init__(**data)
```
Or:
```python
ExampleModel.__init__.__doc__ = 'My modified docstring'
```

I suspect the latter will not be picked up by VSCode though

**Comment by Nathan-Nesbitt** [comment]
I will try out the first one, but I will show you what I was hoping to achieve:

**This is with nothing**
![image](https://user-images.githubusercontent.com/12765521/135319093-68208530-32bc-466f-b178-16cb7b95f702.png)

**This is with the first solution**
![image](https://user-images.githubusercontent.com/12765521/135319262-65771502-41cd-4a0b-bfed-99d28ffab375.png)

**This is what I was hoping to achieve**
![image](https://user-images.githubusercontent.com/12765521/135325002-4fac7bd7-4df9-41e1-ab07-a3890847864f.png)

I think there may be a different way of solving the input types using `pylance` based on [this PR](https://github.com/samuelcolvin/pydantic/pull/2721) but I haven't gotten it working yet.

**Comment by Nathan-Nesbitt** [comment]
Found a way, unfortunately based on that PR the proper solution to this will not be available until a new standard has been adapted in python. The solution involves [making changes to pydantics source](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#applying-to-pydantic) and works remarkably well. The following is using the changes defined in that link, along with pylance:

![image](https://user-images.githubusercontent.com/12765521/135329142-2a51976e-3519-4589-93f9-0004da770f92.png)

No need for the `__init__`. 

The interesting part is that the `pydantic` repo actually [already contains these changes](https://github.com/samuelcolvin/pydantic/blob/c256dccbb383a7fd462f62fcb5d55558eb3cb108/pydantic/main.py#L97-L104) but there hasn't been a release since may.

We can install from GIT instead of PYPI and it works: 

`pip install git+git://github.com/samuelcolvin/pydantic@master#egg=pydantic`
