### ISSUE TITLE
Consider oauth2 library

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#37]
[https://frankie567.github.io/httpx-oauth/fastapi/](httpx-oauth) looks like a drop in option for oauth2. It supports a FastAPI integration as well

From the code, it seems possible to add a custom implementation for Shopify

**Comment by Nathan-Nesbitt** [comment]
This looks interesting, @hillairet this is what I was talking about in regards to removing the environment variables from the library and forcing the developer to pass them into the constructor of OAuth. Maybe this is an easy way to kill 2 birds with 1 stone?

**Comment by qw-in** [comment]
It may be difficult for a few reasons:
- Framed redirect
- URL changes for each shop

Not dealbreakers though
