### ISSUE TITLE
Contain scope of functions for HMAC

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#41]
This TLDR of the current process of validating the HMAC for a request during the oauth process:

1. The main check calls `validate_callback` 
2. `vaidate_callback` extracts the HMAC from the URL
3. `validate_callback` then calls `validate_callback_args` which strips the args
4. The args are then passed to `validate_hmac` (actually a rename of the `validate` function) 
5. The `validate_hmac` immediately calls `calculate_from_message` with the stripped information from the `validate_hmac`.

I think this could be simplified by having each function handle one core component of the process:

1. A function that just calculates the HMAC of a string (and check if it is encoded)
2. A function that takes a URL, strips the HMAC and passes it into function (1) returning the HMAC result
3. A final function that checks the requirements for a callback function, which passes a URL to (2)

**Comment by hillairet** [comment]
The current implementation is fine for now.
