### ISSUE TITLE
Handle wrong store name on OAuth flow

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#49]
Currently if you use the register endpoint for starting the OAuth flow with a store and you fail to provide a valid store name the following error is thrown:

`raise ValueError(f'{shop} is not a shopify shop')`

Which is not handled gracefully on the front end (it throws a 500 internal server error). I think this should probably be some sort of return on this error?

**Comment by qw-in** [comment]
This will be handled in the new oauth flow #46
