### ISSUE TITLE
Handle webhooks in a standardized way

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#51]
Shopify webhooks are defined by Shopify and are therefore very stable.
They can be managed by the same code. The only difference from app to app is the way the webhooks are processed. The way they are registered and deleted is always the same

We should have a simple way to add/define which webhooks an app wants to handle and what processing to do on each, then SPyLib takes care of everything else.

**Comment by hillairet** [comment]
Let's not reinvent the wheel! After all these are endpoints on our end that will receive calls with specific features. So why not reuse the fastapi approach?
```python
from spylib import Webhooker

webhooker = Webhooker(secret_key)

@webhooker.register('products/update')
async def product_updated(productdata: dict):
    # Processing of the product data here

app = FastAPI()
app.add_route('/webhooks', webhooker)
```

SPyLib would (ideally) automatically check at the startup of the app, in the background, that all the webhooks are properly registered on Shopify and if not, register them. Potentially it could clean up removed webhooks. [some reusable code here](https://github.com/SatelCreative/st-pim/blob/main/server/resources/store/webhook.py)
Also the `product_updated` function would be run in the background by a worker waiting for data from a queue. That guarantees smoother processing of the data. [Example of a Redis queue](https://github.com/SatelCreative/st-pim/blob/9c31fbc6f6738e16444ea7d5cbb7fd0a2f063e32/server/webapp/products_app.py#L229) but we'd start with an in memory queue here

**Comment by hillairet** [comment]
Interesting to have that in mind as a feature:
[Specify private metafields for webhooks using GraphQL Admin API](https://shopify.dev/changelog/specify-private-metafields-for-webhooks-using-graphql-admin-api)

**Comment by hillairet** [comment]
Some more ideas.
I think we should use the same approach as what we did for the tokens with abstract classes.
This way we can similarly to the tokens, have `load` and `save` type of methods to store the webhook information and retrieve it.

Could look something like that:

```python
class WebhookHandlerABC(BaseModel, ABC):
    @abstractmethod
    async def save(self):
        """Save to persistent storage"""
        pass

    @abstractclassmethod
    async def load(cls, store_name: str):
        """Retrieve from the persistent storage for a given store"""
        pass

    @abstractclassmethod
    async def push_to_queue(cls, payload: WebhookPayload):
        """Function called to add the given webhook payload to the processing queue"""
        pass

    @abstractclassmethod
    async def pull_from_queue(cls):
        """Function called to add the given webhook payload to the processing queue"""
        pass

    async def _register_webhook(self, ...
```

**Comment by hillairet** [comment]
Let's plan this properly with a github discussion first then come back to this issue

**Comment by qw-in** [comment]
#105
