### ISSUE TITLE
Simplify HMAC code

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#67]
Based on this discussion: https://github.com/SatelCreative/satel-spylib/issues/50#issuecomment-984181701_

We can move the HMAC code into the individual validation folders for each portion of the library.

**Comment by Nathan-Nesbitt** [comment]
@hillairet I have the solution written up based on this PR, but I am running into an issue with how the Oauth section is being tested right now:

https://github.com/SatelCreative/satel-spylib/blob/9210b4ec5ae535395fc8b43751eeaeba8ee9b007/tests/oauth/test_base.py#L64

This is just one big test of a single run through the OAuth process. By making this change, it breaks the middle portion of the test. Can I break the tests for OAuth into smaller tests for each part of the OAuth process? For example instead of one big function `test_oauth` we could instead test the following:

1. `test_shopify_callback`
2. `test_shopify_auth`
3. `test_app_redirect`
4. `test_oauth_init_url`
5. `test_get_token`

This way it should be easier to detect when and what has broken, and using this format I should be able to fix the current error in the middle a little easier.

I think there are likely more functions to test, there are just the top 5 that I see by skimming the OAuth portion of the library.

**Comment by Nathan-Nesbitt** [comment]
** When I say it breaks the middle of the test, I mean that the test depends on one of these functions that I am removing, and I will have to re-write a portion of the test to get the functionality back.

**Comment by hillairet** [comment]
Before you spend too much time on refactoring the tests, do you understand why it fails?
It shouldn't ... if the code does the right thing ...
And the test should tell you where there is a problem.

**Comment by Nathan-Nesbitt** [comment]
> Before you spend too much time on refactoring the tests, do you understand why it fails? It shouldn't ... if the code does the right thing ... And the test should tell you where there is a problem.

Sorry @hillairet  I hit enter while typing the original comment. To answer your question, I know why it is failing as the original tests use a method that I will be removing. They are currently doing the following:

https://github.com/SatelCreative/satel-spylib/blob/9210b4ec5ae535395fc8b43751eeaeba8ee9b007/tests/oauth/test_base.py#L101-L102

This is the only time we really need this method, and if we split it into smaller parts there's no need for this call at all. As I can define it as a constant value into the test.

Same issue with this line:

https://github.com/SatelCreative/satel-spylib/blob/9210b4ec5ae535395fc8b43751eeaeba8ee9b007/tests/oauth/test_base.py#L134-L135

**Comment by Nathan-Nesbitt** [comment]
I think the comments in this section would potentially indicate we need tests for:

1. `login` (OnlineToken)
2. `installation` (OfflineToken)

I can also remove a lot of the constant definitions at the top, as they are re-definitions of the information in [`token_classes.py`](https://github.com/SatelCreative/satel-spylib/blob/main/tests/token_classes.py)

**Comment by hillairet** [comment]
Doesn't feel relevant anymore.
