### ISSUE TITLE
Session tokens issues

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#75]
First, the new form of the session tokens does not appear to match the docs `README.md`. I attempted to use depends however there seems to be no mechanism in the function itself to extract a header from the request? The method was also called `from_header` rather than `decode_token_from_header` which was referenced in the docs

A suggestion is to write tests based on your examples in the README - that way if they break it will be clear what needs to be updated

An issue I am having to work around now is that shopify does not actually pass the `jti` as an int. At least in the session token I received it was a string ('3512a085-ee9a-4914-b252-3aabcd1ada14')

For your convenience here is a full session token payload:

```js
{
  "iss": "https://satel-products.myshopify.com/admin",
  "dest": "https://satel-products.myshopify.com",
  "aud": "2ca57b9f8ea64fc449ca4d20610884ec",
  "sub": "78980514043",
  "exp": 1638925238,
  "nbf": 1638925178,
  "iat": 1638925178,
  "jti": "3512a085-ee9a-4914-b252-3aabcd1ada14",
  "sid": "38a01da7a45fbc47b07ddee21155e017d3e3e04b646e766835135021d24e39ee"
}
```

Edit:

This workaround seems to work:

```python
class MySessionToken(SessionToken):
    jti: str
```

**Comment by Nathan-Nesbitt** [comment]
@qw-in I created a PR which should address these issues. Are you able to send me a full request with the session token? I want to check something!

**Comment by qw-in** [comment]
@Nathan-Nesbitt I am unable to log in to Shopify partners but will get you one when that is resolved :sweat_smile:
