### ISSUE TITLE
Dependency versions are too strict

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#77]
Especially the packages that have not hit `1.0.0` yet. At the moment spylib insists on specifically "fastapi@0.68". [Here is some helpful documentation from poetry that could help make it a little more flexible](https://python-poetry.org/docs/dependency-specification/)

**Comment by hillairet** [comment]
@qw-in The caret doesn't do what I expected! We will fix that right away by using `=>` instead of `^` in the dependency.

**Comment by qw-in** [comment]
Bit of a gotcha with it is that they behave differently if there is a leading 0 in the version number
