### ISSUE TITLE
Setup standard logging function

### ISSUE THREAD

**Issue by rahulpatidar0191** [SatelCreative/spylib#78]
Original issue: https://github.com/SatelCreative/DevOps-IT/issues/59

Update [the standard logging function](https://github.com/SatelCreative/spylib/blob/main/spylib/logs.py) that would:
* Use ~logz.io~ grafana for info level in production
* Push debug level to local files for all environments

Potentially use SB PIM as test ground

Ok we're gonna need more config parameters so we need to modify the structure for logs in spylib to have a folder and not just one file.

This was implemented in the [Toolip library](https://github.com/SatelCreative/toolip/blob/main/toolip/utils/logs.py) and should be reviewed to be optimized for our cloud Sentry deployment.

**Comment by hillairet** [comment]
@rahulpatidar0191 As you pointed it out, it was implemented in toolip so it doesn't belong here.
