### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#84]
Our current dependencies were chosen out of habit and convenience without considering that this is a library so we should have a minimal set of dependencies:

- [x] Raise an exception with a clear message to install fastapi whenever `spylib/oauth/router.py` is loaded and fastapi cannot be imported.
- [x] Remove loguru and use the standard library logger instead.
- [x] Copy paste code from the shortuuid library that we need to make our `get_unique_id` independent of shortuuid
- [x] Move nest-asyncio to dev dependencies (must have been put as main dependency by accident)

**Comment by hillairet** [comment]
Well it turns out that the rest API uses `status` from Starlette so the best is probably to copy paste the whole status module from Starlette to have our own.

**Comment by hillairet** [comment]
nest-asyncio was removed in #98

**Comment by lishanl** [comment]
still have 2 items remaining

**Comment by lishanl** [comment]
> Well it turns out that the rest API uses `status` from Starlette so the best is probably to copy paste the whole status module from Starlette to have our own.

Do we still want to do this as well? Maybe create another issue for it? @hillairet
