### ISSUE TITLE
Handle online token for API calls

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#9]
Currently the Store class is designed and handles only the offline token.
SPyLib needs to handle also the online token somehow.
This may require a change of the whole Store class API.

**Comment by hillairet** [comment]
One thing we could do is have a Staff class pretty much the same as the Store class but with different ID (store_id+staff_id for the Staff class). So both classes would inherit the methods from a ShopifyAPI base class.

**Comment by Nathan-Nesbitt** [comment]
Could we instead change the token to be its own class which is then passed into the main Store class? This would allow us to keep the same structure for the Store but change how the user of the library wants this logic/auth to work.

**Comment by hillairet** [comment]
This will be properly handled in #18 so let's close that one.
