### ISSUE TITLE
Add gitmoji in PR title enforcement

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#92]
Let's start documenting our commits to main properly to make our changelog better as soon as possible.
Please add the github action to enforce the gitmoji in PR titles.

**Comment by rahulpatidar0191** [comment]
I came across this recently to generate changelog for a release 
https://github.com/marketplace/actions/generate-release-changelog

**Comment by hillairet** [comment]
Ok this automation would be nice so it's all in Github but we need it to create the release only on tags of the format `XX.YY.ZZ` and not `XX.YY.ZZ-*` such as `1.2.3-beta1`. The idea is to see the changelog between the releases. I'm pretty sure having prereleases would mess this up. So could you skip/exit if there is `-` in the tag?

**Comment by rahulpatidar0191** [comment]
We can do something like this to ignore tags with `-`

```yml
on:
  push:
    tags-ignore:
      - '*-*' # We don't want this to run on release

**Comment by hillairet** [comment]
@rahulpatidar0191 The repo has a good amount of activity right now. It'd be good to have this done. Even Lishan forgets the gitmojis!  :wink:
