### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#96]
It is nice to provide documentation on setting up the development environment, commands, expectations, etc.

Examples:
- [fastapi](https://github.com/tiangolo/fastapi/blob/master/CONTRIBUTING.md)
- [pydantic](https://pydantic-docs.helpmanual.io/contributing/)

**Comment by qw-in** [comment]
#87 could be included within this scope

**Comment by hillairet** [comment]
You mean like this file?
;-)
https://github.com/SatelCreative/spylib/blob/main/docs/development-contributing.md

It'll be in the next version of the documentation that will be deployed soon once we make 0.5 and it's coming super soon now that stuff like the dependencies are in a much better state.

**Comment by qw-in** [comment]
Ahh, a link from README.md or CONTRIBUTING.md would probably help people find it :wink:

**Comment by hillairet** [comment]
Because of the fact that we are generating the docs using mkdocs, a link from the README is problematic but indeed a CONTRIBUTING file is the way to go.
