### ISSUE TITLE
Website syntax highlighting

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#97]
Currently, syntax highlighting does not appear to be working on the documentation website:

https://satelcreative.github.io/spylib/#implement-token-classes

**Comment by hillairet** [comment]
Based on how it's done in fastapi, I believe we need to use [mdx-include](https://pypi.org/project/mdx-include/)

**Comment by lishanl** [comment]
looks like it also uses [codehilite](https://python-markdown.github.io/extensions/code_hilite/) extension
https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax-highlighting

**Comment by hillairet** [comment]
Right but this thing is a bit confusing @lishanl.
I believe codehilite is part of some other package ... check what is done in fastapi.
